plugins {
    id 'com.android.application'
}

android {
    compileSdk 33

    defaultConfig {
        applicationId "com.lolstudio.lizhimusic"
        minSdk 21
        targetSdk 25
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    lint {
        abortOnError false
        checkReleaseBuilds false
    }

    aaptOptions {
        noCompress 'mp3'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
